#!/usr/bin/env sh

# Maven Wrapper Script
# Generated by Apache Maven
# https://maven.apache.org/wrapper/ 

# Make sure you use the correct Java version
if [ -z "${JAVA_HOME}" ]; then
  echo "JAVA_HOME is not set. Please set it to your JDK installation directory."
  exit 1
fi

# Set the wrapper jar and properties file
WRApperJar="demo/mvnw.jar"
WRApperProperties="demo/mvnw.properties"

# Check if the wrapper jar exists
if [ ! -f "$WRApperJar" ]; then
  echo "Wrapper jar not found!
"
  exit 1
fi

# Execute the wrapper
exec java -cp "$WRApperJar" org.apache.maven.wrapper.MavenWrapperMain "$@"